import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'


export default function Home () {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <nav className={styles.mainnav}>
        <ul>

          <Link href='/'> <a><li>Home</li></a></Link>
          <Link href='/about'> <a><li>About</li></a></Link>
          <Link href='/blog'> <a><li>Blog</li></a></Link>
          <Link href='/contact'> <a><li>Contact</li></a></Link>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>Hunting Coder</h1>
        <p className={styles.description}>
          A blog for hunting coders by hunting coder{' '}
        </p>
        <div className={styles.blogs}>
          <h2>Popular Blogs</h2>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
        </div>
      </main>
    </>
  )
}
