import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import dynamic from "next/dynamic";



function Home () {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className={styles.main}>
      <style jsx>
        {
          `
          h2{
            font-size: 38px;
          }
          h3{
            font-size: 28px;
          }`
        }
      </style>
        <h1>Hunting Coder</h1>
        <div className={styles.imagewrap}>
          <Image className={styles.myImg} src="/homeimg.jpg" width={237} height={158} alt="Home image" />
        </div>
        <p className={styles.description}>
          A blog for hunting coders by hunting coder{' '}
        </p>
        <div className='blog'>
          <h2>Popular Blogs</h2>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
        </div>
      </main>
    </>
  )
}
export default dynamic (() => Promise.resolve(Home), {ssr: false})

